version: '3.8'

services:

  accenturebackendtest:
    build:
      context: .
    container_name: accenturebackendtest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_ATLAS_URI}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge