version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  to_do_list_backend:
    build:
      context: .
    container_name: to_do_list_backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/todo_db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
