spring:
  application:
    name: todoapp
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/todo_db}
      auto-index-creation: true
  webflux:
    base-path: /api/v1

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.accenture.todoapp: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

